eureka:
    client:
        fetch-registry: true
        instance:
            hostname: localhost
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_SERVER:http://localhost:9090/eureka}
